import type { FinancialSnapshot } from '@/engine/types/inputs'

// Canonical FinancialSnapshot in CLP for the Kumbre MVP.
// Represents Kali's personal + business finances as of June 2026.
export const NOW = '2026-06-28T00:00:00Z'

export const personalSnapshot: FinancialSnapshot = {
  asOf: NOW,
  accounts: [
    { id: 'acc-1', name: 'Cuenta Corriente', kind: 'checking', balance: 4_820_000, isLiquid: true },
    { id: 'acc-2', name: 'Cuenta Ahorro', kind: 'savings', balance: 10_500_000, isLiquid: true },
    { id: 'acc-3', name: 'Inversiones APV', kind: 'investment', balance: 15_200_000, isLiquid: false },
  ],
  transactions: [
    {
      id: 'tx-sueldo',
      accountId: 'acc-1',
      amount: 3_500_000,
      kind: 'income',
      date: '2026-06-01T10:00:00Z',
      isRecurring: true,
      frequency: 'monthly',
      categoryId: 'cat-sueldo',
      categoryName: 'Sueldo',
      description: 'Sueldo junio',
      tags: [],
    },
    {
      id: 'tx-arriendo',
      accountId: 'acc-1',
      amount: 850_000,
      kind: 'expense',
      date: '2026-06-01T12:00:00Z',
      isRecurring: true,
      frequency: 'monthly',
      categoryId: 'cat-arriendo',
      categoryName: 'Arriendo',
      description: 'Arriendo',
      tags: [],
    },
    {
      id: 'tx-super',
      accountId: 'acc-1',
      amount: 180_000,
      kind: 'expense',
      date: '2026-06-10T14:30:00Z',
      isRecurring: false,
      categoryId: 'cat-alimentos',
      categoryName: 'Alimentación',
      description: 'Supermercado Jumbo',
      tags: [],
    },
    {
      id: 'tx-transporte',
      accountId: 'acc-1',
      amount: 45_000,
      kind: 'expense',
      date: '2026-06-15T08:00:00Z',
      isRecurring: true,
      frequency: 'monthly',
      categoryId: 'cat-transporte',
      categoryName: 'Transporte',
      description: 'Transporte mensual',
      tags: [],
    },
    {
      id: 'tx-ocio',
      accountId: 'acc-1',
      amount: 65_000,
      kind: 'expense',
      date: '2026-06-20T20:00:00Z',
      isRecurring: false,
      categoryId: 'cat-ocio',
      categoryName: 'Ocio',
      description: 'Cena cumpleaños',
      tags: ['social'],
    },
    {
      id: 'tx-salud',
      accountId: 'acc-1',
      amount: 35_000,
      kind: 'expense',
      date: '2026-06-22T09:00:00Z',
      isRecurring: false,
      categoryId: 'cat-salud',
      categoryName: 'Salud',
      description: 'Consulta médica',
      tags: [],
    },
  ],
  debts: [
    {
      id: 'debt-1',
      name: 'Crédito Personal BCI',
      kind: 'personal',
      originalAmount: 5_000_000,
      remainingAmount: 3_200_000,
      monthlyPayment: 180_000,
      interestRate: 0.12,
      startDate: '2025-01-01T00:00:00Z',
      endDate: '2027-06-01T00:00:00Z',
    },
  ],
  investments: [
    {
      id: 'inv-1',
      name: 'Fondo Mutuo Banchile',
      kind: 'fund',
      currentValue: 8_000_000,
      avgCost: 6_500_000,
      quantity: 1,
      expectedAnnualReturn: 0.07,
    },
  ],
  objectives: [
    {
      id: 'obj-casa',
      name: 'Casa propia',
      targetAmount: 100_000_000,
      currentAmount: 67_400_000,
      targetDate: '2029-01-01T00:00:00Z',
      priority: 1,
      status: 'on_track',
      linkedFundIds: ['fund-1'],
    },
    {
      id: 'obj-europa',
      name: 'Europa',
      targetAmount: 5_000_000,
      currentAmount: 1_900_000,
      targetDate: '2027-08-01T00:00:00Z',
      priority: 2,
      status: 'at_risk',
      linkedFundIds: ['fund-2'],
    },
    {
      id: 'obj-emergencia',
      name: 'Fondo Emergencia',
      targetAmount: 9_000_000,
      currentAmount: 8_500_000,
      targetDate: '2026-12-01T00:00:00Z',
      priority: 3,
      status: 'on_track',
      linkedFundIds: ['fund-3'],
    },
  ],
  funds: [
    {
      id: 'fund-1',
      name: 'Fondo Casa',
      currentAmount: 67_400_000,
      targetAmount: 100_000_000,
      objectiveIds: ['obj-casa'],
      allocationRule: { trigger: 'on_income', percentage: 0.20 },
    },
    {
      id: 'fund-2',
      name: 'Fondo Europa',
      currentAmount: 1_900_000,
      targetAmount: 5_000_000,
      objectiveIds: ['obj-europa'],
      allocationRule: { trigger: 'on_income', percentage: 0.05 },
    },
    {
      id: 'fund-3',
      name: 'Fondo Emergencia',
      currentAmount: 8_500_000,
      targetAmount: 9_000_000,
      objectiveIds: ['obj-emergencia'],
      allocationRule: { trigger: 'on_income', percentage: 0.10 },
    },
  ],
  rules: [
    { id: 'rule-savings', kind: 'min_savings_rate', label: 'Ahorro mínimo 20%', value: 0.20, priority: 'high', enabled: true },
    { id: 'rule-dti', kind: 'max_debt_to_income', label: 'Deuda máxima 35% ingreso', value: 0.35, priority: 'critical', enabled: true },
    { id: 'rule-emergency', kind: 'emergency_fund_months', label: 'Fondo emergencia 3 meses', value: 3, priority: 'high', enabled: true },
  ],
}
